export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";


export const CREATE_USER = "CREATE_USER";
export const RETRIEVE_USER = "RETRIEVE_USER";
export const UPDATE_USER = "UPDATE_USER";
export const DELETE_USER = "DELETE_USER";



export const CREATE_TICKET = "CREATE_TICKET";
export const RETRIEVE_TICKET = "RETRIEVE_TICKET";
export const UPDATE_TICKET = "UPDATE_TICKET";
export const DELETE_TICKET = "DELETE_TICKET";

export const CREATE_PERFORMANCE = "CREATE_PERFORMANCE";
export const RETRIEVE_PERFORMANCE = "RETRIEVE_PERFORMANCE";
export const UPDATE_PERFORMANCE = "UPDATE_PERFORMANCE";
export const DELETE_PERFORMANCE = "DELETE_PERFORMANCE";
